# Ajustando os binarios /sbin/poweroff, /sbin/reboot e /sbin/shutdown
# Necessario alterar esses binarios para que o host consiga desligar e reinciar
# Os binarios originais nao consegue desmontar os containers do docker e falha no processo
---
- hosts: all
  gather_facts: True
#  remote_user: linux
#  become: yes
#  become_user: root
#  become_method: sudo

  tasks:
   - name: Fazendo backup do arquivo da zona East Brasil  
     copy:
       remote_src: yes
       force: no
       backup: yes
       src: /usr/share/zoneinfo/Brazil/East
       dest: /usr/share/zoneinfo/Brazil/East.bkp

   - name: Copiando o arquivo .zic atualizado
     copy:
       force: no
       src:  verao-2029.zic
       dest: /usr/share/zoneinfo/Brazil/

   - name: Atualizando timezone para horario de verao
     raw: zic /usr/share/zoneinfo/Brazil/verao-2029.zic
